### ISSUE TITLE
data package

### ISSUE THREAD

**Issue by weizhon** [RaphiMC/ViaBedrock#112]
The server entering bedrock edition can't send data packets, but can accept data packets.

**Comment by RaphiMC** [comment]
Please provide more details (logs, screenshots, videos)

**Comment by weizhon** [comment]
https://github.com/user-attachments/assets/535dc668-f653-4869-a820-fbced083f322

**Comment by RaphiMC** [comment]
ViaBedrock is currently in alpha stage and most things aren't working yet. See a list of features here: https://github.com/RaphiMC/ViaBedrock?tab=readme-ov-file#features
