### ISSUE TITLE
Not an issue, but Is it bad idea to use this Library on Geyser Extension(Excluding Geyser-ViaProxy)?

### ISSUE THREAD

**Issue by Outfit8TSB** [RaphiMC/ViaBedrock#131]
So Recently I created the Geyser Extension Called JavaEdition2BedrockEdition To Solve The Puzzle as Part of My ViaVersion Unofficial Addon(see GAME-CLI-SRV-DEV/ViaVersionProtocolSupport#6), 

Here is the Puzzle what i tried to solve.
I Tried GAME-CLI-SRV-DEV/ViaProxyWebAuthenticator and ayunami2000/AyunViaProxyShared to solve this.

Probably took 2 month to solve it.

So Here is the puzzle.
So, a man named CensingSmile123(BE, Which is Me), wanted to invite RK_01(JE, You) to @Tim203's Birthday server.
Unfortunately, @Tim203 has only invited Bedrock Players(Installed KejonaMC/GeyserBlockJavaPlayers), so i could come to his birthday party, but you couldn't.
So You Try to use @Lenni0451's ViaProxy Server(which is address_port_version.viaproxy.lenni0451.net), But You couldn't, because of course, you would need a OpenAuthMod because @Tim203's Server is Online Mode. In This Puzzle, You Are Vanilla Player. So you couldn't join.
So You have to try @creeper123123321's VIAaaS(which is address._pport._v(version/Auto)._uUsername._o(t/f/A).via.re.yt.nom
br:25565), But VIAaaS Don't support ViaBedrock. So you couldn't come and you send text message to @Tim203, that you aren't his friends anymore. (this is just a theory. Do not take it seriously.)
so i realized, after fail of 2 attempts, the answer must be...
Geyser Extension.

If VIAaaS is not supporting ViaBedrock, Installing Geyser Extension That Support ViaBedrock, put it and link the server you want to go, is the best solution to bridge the gap, i ever thinked.

And Of Course, If it's Floodgate then it requires ViaVersion/VIAaaS#53 to be implemented.

Is it a bad idea to do it? I mean,i know that library is not complete, but it's good idea for me.

**Comment by RaphiMC** [comment]
Stop creating spam issues or you will be blocked
