### ISSUE TITLE
ViaBedrock

### ISSUE THREAD

**Issue by DanyX0001** [RaphiMC/ViaBedrock#134]
I break the blocks but i dont see them drop on the floor i need to rejoin the realm that i can see in my Inventory

**Comment by RaphiMC** [comment]
Inventory interactions aren't implemented yet. Thats why its not working

**Comment by DanyX0001** [comment]
Can you fix it?

**Comment by RaphiMC** [comment]
Eventually, but I am currently working on block breaking. Inventory interactions are planned next.
