### ISSUE TITLE
malformed packet disconnect

### ISSUE THREAD

**Issue by mmarchjr** [RaphiMC/ViaBedrock#14]
I got this issue and it says to put it here, so 
[error](https://i.postimg.cc/sz6ZwLWY/Screenshot-2023-04-16-080659.png)

**Comment by RaphiMC** [comment]
What server did you join? And please send the log (in the logs folder of ViaProxy) where the error ocurred

**Comment by mmarchjr** [comment]
shoot, it was a bedrock realm that I did an ip tracer to get the address. i was trying to join with a fabric client. right after I sent this, I factory reset my computer, but I will try to recreate it

**Comment by RaphiMC** [comment]
Closed due to inactivity
