### ISSUE TITLE
Error while trying to join

### ISSUE THREAD

**Issue by craciu25yt** [RaphiMC/ViaBedrock#17]
when I join cubecraft bedrock edition it fails to download the resourcepacks and after clicking proceed I get send to the main screen
![image](https://github.com/RaphiMC/ViaBedrock/assets/48807342/156fd0d1-3ec0-4d5f-b7dc-04b80241f54f)

**Comment by RaphiMC** [comment]
Send the latest.log of the client and ViaProxy. Make sure to test with a 1.19.4 client

**Comment by craciu25yt** [comment]
[latest.log](https://github.com/RaphiMC/ViaBedrock/files/11470079/latest.log)
I'm using ViaFabricPlus so there's no ViaProxy logs

**Comment by RaphiMC** [comment]
ViaBedrock is currently in very early development and to rule out any errors of others (Mod devs for example), the only valid way to submit an error report is to use ViaProxy as stated in the README and test using a vanilla 1.19.4 client. I am closing this issue now and if you experience the error with ViaProxy you can open a new issue. If not you have to report that to ViaFabricPlus
