### ISSUE TITLE
forge port 🥺

### ISSUE THREAD

**Issue by davedberry** [RaphiMC/ViaBedrock#64]
please add a forge port 🥺

**Comment by RaphiMC** [comment]
ViaBedrock works with all clients and doesn't care about the modloader

**Comment by Lncvrt** [comment]
> ViaBedrock works with all clients and doesn't care about the modloader

Because of ViaFabric right?

**Comment by Lncvrt** [comment]
well ViaForge too ig

**Comment by Gaming32** [comment]
It is not a mod. It is a library. It cares about nothing about the client.

**Comment by Lncvrt** [comment]
> It is not a mod. It is a library. It cares about nothing about the client.

Oh true I guess. I don't really understand how viaver stuff works lol

**Comment by Outfit8TSB** [comment]
@Lncvrt quit fooling around man, use ViaProxy.

**Comment by Lncvrt** [comment]
> @davedberry  quit fooling around man, use ViaProxy.

i personally don't like via proxy but that's just me
